# Generated by Django 5.0.4 on 2024-05-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productimagesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimagesetting',
            options={'ordering': ['id']},
        ),
    ]
