# Generated by Django 5.0.4 on 2024-05-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogpagesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='blog_images/', verbose_name='Image'),
        ),
    ]
