# Generated by Django 5.0.4 on 2024-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_blogpagesetting_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagesetting',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='blogpagesetting',
            name='description1',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='blogpagesetting',
            name='description2',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='blogpagesetting',
            name='description3',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='blogpagesetting',
            name='detail1',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='blogpagesetting',
            name='detail2',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='blogpagesetting',
            name='fileSmall',
            field=models.ImageField(blank=True, default='', upload_to='blog_images/', verbose_name='Image'),
        ),
    ]
