# Generated by Django 5.0.4 on 2024-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogpagesetting_comment_blogpagesetting_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=254)),
                ('department', models.CharField(blank=True, default='', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='contactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, default='', max_length=254)),
                ('tel', models.CharField(blank=True, default='', max_length=254)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('calisma_week', models.CharField(blank=True, default='', max_length=254)),
                ('calisma_weekend', models.CharField(blank=True, default='', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
