# Generated by Django 5.0.4 on 2024-05-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_commentsetting_contactsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsetting',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='comment_images/', verbose_name='Image'),
        ),
    ]
